# Generated by Django 4.1.4 on 2022-12-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jimbo_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Muscles',
            new_name='Muscle',
        ),
    ]
