# Generated by Django 4.1.4 on 2023-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimbo_server', '0003_exercise_comment_exercise_current_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='public',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
