# Generated by Django 4.1.4 on 2023-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jimbo_server', '0004_day_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='public',
        ),
        migrations.AddField(
            model_name='workout',
            name='public',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
